repo_url: https://github.com/jonh-carvalho/PBE_25.2_8002
site_author: Jonh Carvalho
site_name: Validação de Estágios - PBE_26.1_8002_IV
site_description: Documentação do projeto de validação de estágios
copyright: Copyright © 2026, Jonh Carvalho, Rafael Correa, Heitor Lima, Bernardo Fontes, Caio Salomão, Carlos Vinícius


nav:
  - Home: index.md
  - Iniciação:
      - Index: Iniciacao/index.md
      - Pesquisa: Iniciacao/pesquisa.md
      - 5W2H: Iniciacao/5w2h.md
      - Brainstorming: Iniciacao/brainstorm.md
      - Mapa Mental: Iniciacao/mapa_mental.md
      - Prototipagem Baixa Fidelidade: Iniciacao/prototipo_baixa_fidelidade.md
  - Elaboração:
      - Index: Elaboracao/index.md
      - Requisitos: Elaboracao/requisitos.md
      - Casos de Uso: Elaboracao/casos_de_uso.md
      - Diagrama de Classes: Elaboracao/diagrama_de_classes.md
      - Protótipo de Alta Fidelidade: Elaboracao/prototipo_alta_fidelidade.md
  - Construção:
      - Index: Construcao/index.md
      - Git Issues: Construcao/git_issues.md
      - GitHub Projects: Construcao/github_projects.md
      - CodeSpace: Construcao/codespace.md
  - Transição:
      - Index: Transicao/index.md
      - Manual do Usuário: Transicao/manual_usuario.md

theme:
  name: material
  language: pt-BR
  logo: assets/ibmec_logo.png
  favicon: assets/ibmec_logo.png

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Alternar para modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Alternar para modo claro

  features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  font:
    text: Roboto
    code: Roboto Mono

  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji ''
      emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

extra_css:
  - css/extra.css