# Generated by Django 6.0 on 2026-05-19 20:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import val_estagio.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('administração', 'Administração'), ('análise e Desenvolvimento de Sistemas', 'Análise e desenvolvimento de sistemas'), ('Arquitetura e Urbanismo', 'Arquitetura e urbanismo'), ('ciência de dados e inteligência artificial', 'Ciência de Dados e Inteligência Artificial'), ('ciências Contábeis', 'Ciências contábeis'), ('direito', 'Direito'), ('ciências Econômicas', 'Ciências econômicas'), ('comunicação social - publicidade e propaganda', 'Comunicação Social - Publicidade e Propaganda'), ('engenharia civil', 'Engenharia Civil'), ('engenharia de produção', 'Engenharia de Produção'), ('engenharia da computação', 'Engenharia da Computação'), ('engenharia de software', 'Engenharia de Software'), ('relações internacionais', 'Relações Internacionais')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('endereco_empresa', models.CharField(max_length=180, verbose_name='Endereço da Empresa')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[val_estagio.validators.validar_cnpj])),
            ],
        ),
        migrations.CreateModel(
            name='Seguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apolice_seguro', models.PositiveIntegerField(unique=True, verbose_name='Apolice de Seguro')),
                ('nome_seguradora', models.CharField(max_length=100, verbose_name='Nome da Seguradora')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('unidade', models.CharField(choices=[('barra', 'Barra'), ('botafogo', 'Botafogo')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('negocios', 'Negócios'), ('tecnologia', 'Tecnologia'), ('financas', 'Finanças'), ('direito', 'Direito'), ('engenharia', 'Engenharia')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cursos', models.ManyToManyField(blank=True, to='val_estagio.curso')),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=12, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[val_estagio.validators.validar_cpf])),
                ('dt_nascimento', models.DateField()),
                ('procurando_estagio', models.BooleanField(default=True)),
                ('horas_estagio', models.IntegerField(default=0)),
                ('periodo', models.PositiveIntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='val_estagio.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de inicio')),
                ('data_fim', models.DateField(verbose_name='Data de fim')),
                ('carga_horaria', models.PositiveIntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='val_estagio.aluno')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='val_estagio.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioSemestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_estagiadas', models.PositiveIntegerField()),
                ('em_aberto', models.BooleanField(default=True)),
                ('semestre', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='O semestre deve estar no formato 26.1 ou 26.2', regex='^\\d{2}\\.[12]$')])),
                ('data_envio', models.DateField(verbose_name='Data de envio')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='val_estagio.aluno')),
                ('estagio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='val_estagio.estagio')),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_funcionario', models.CharField(max_length=12, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auxilio_bolsa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_inicio', models.DateField(verbose_name='Data de inicio')),
                ('data_fim', models.DateField(verbose_name='Data de fim')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='val_estagio.aluno')),
                ('empresa_contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='val_estagio.empresa', verbose_name='Empresa Contratante')),
                ('seguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='val_estagio.seguradora')),
            ],
        ),
        migrations.AddField(
            model_name='estagio',
            name='tce',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='val_estagio.tce'),
        ),
    ]
