# Generated by Django 6.0 on 2026-05-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(choices=[('administração', 'Administração'), ('analise e desenvolvimento de sistemas', 'Análise e Desenvolvimento de Sistemas'), ('arquitetura e urbanismo', 'Arquitetura e Urbanismo'), ('ciencia de dados e inteligencia artificial', 'Ciência de Dados e Inteligência Artificial'), ('ciencias contabeis', 'Ciências Contábeis'), ('direito', 'Direito'), ('ciencias economicas', 'Ciências Econômicas'), ('comunicacao social - publicidade e propaganda', 'Comunicação Social - Publicidade e Propaganda'), ('engenharia civil', 'Engenharia Civil'), ('engenharia de producao', 'Engenharia de Produção'), ('engenharia da computacao', 'Engenharia da Computação'), ('engenharia de software', 'Engenharia de Software'), ('relacoes internacionais', 'Relações Internacionais')], max_length=100, unique=True),
        ),
    ]
