# Generated by Django 6.0 on 2026-05-28 19:45

import encrypted_model_fields.fields
import val_estagio.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=encrypted_model_fields.fields.EncryptedCharField(validators=[val_estagio.validators.validar_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=encrypted_model_fields.fields.EncryptedCharField(primary_key=True, serialize=False, validators=[val_estagio.validators.validar_cnpj], verbose_name='CNPJ'),
        ),
    ]
