# Generated by Django 6.0.5 on 2026-05-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
