# Generated by Django 6.0.5 on 2026-05-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordenador',
            options={'verbose_name': 'Coordenador', 'verbose_name_plural': 'Coordenadores'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
