# Generated by Django 6.0 on 2026-05-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(choices=[('administração', 'Administração'), ('análise e Desenvolvimento de Sistemas', 'Análise e desenvolvimento de sistemas'), ('Arquitetura e Urbanismo', 'Arquitetura e urbanismo'), ('ciência de dados e inteligência artificial', 'Ciência de Dados e Inteligência Artificial'), ('ciências Contábeis', 'Ciências contábeis'), ('direito', 'Direito'), ('ciências econômicas', 'Ciências Econômicas'), ('comunicação social - publicidade e propaganda', 'Comunicação Social - Publicidade e Propaganda'), ('engenharia civil', 'Engenharia Civil'), ('engenharia de produção', 'Engenharia de Produção'), ('engenharia da computação', 'Engenharia da Computação'), ('engenharia de software', 'Engenharia de Software'), ('relações internacionais', 'Relações Internacionais')], max_length=100, unique=True),
        ),
    ]
