# Generated by Django 6.0 on 2026-05-21 10:14

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import val_estagio.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0002_alter_curso_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatoriosemestral',
            options={'verbose_name': 'Relatório Semestral', 'verbose_name_plural': 'Relatórios Semestrais'},
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[val_estagio.validators.validar_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.PROTECT, to='val_estagio.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dt_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='horas_estagio',
            field=models.IntegerField(default=0, verbose_name='Horas de Estágio'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='periodo',
            field=models.PositiveIntegerField(verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='procurando_estagio',
            field=models.BooleanField(default=False, verbose_name='Procurando Estágio'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR', verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(db_column='matricula', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='area',
            field=models.CharField(choices=[('negocios', 'Negócios'), ('tecnologia', 'Tecnologia'), ('financas', 'Finanças'), ('direito', 'Direito'), ('engenharia', 'Engenharia')], max_length=100, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(choices=[('administração', 'Administração'), ('analise e desenvolvimento de sistemas', 'Análise e Desenvolvimento de Sistemas'), ('arquitetura e urbanismo', 'Arquitetura e Urbanismo'), ('ciencia de dados e inteligencia artificial', 'Ciência de Dados e Inteligência Artificial'), ('ciencias contabeis', 'Ciências Contábeis'), ('direito', 'Direito'), ('ciencias economicas', 'Ciências Econômicas'), ('comunicacao social - publicidade e propaganda', 'Comunicação Social - Publicidade e Propaganda'), ('engenharia civil', 'Engenharia Civil'), ('engenharia de producao', 'Engenharia de Produção'), ('engenharia da computacao', 'Engenharia da Computação'), ('engenharia de software', 'Engenharia de Software'), ('relacoes internacionais', 'Relações Internacionais')], max_length=100, unique=True, verbose_name='Nome do Curso'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, validators=[val_estagio.validators.validar_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR', verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='uf',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='cargahorariasemanal',
            field=models.IntegerField(verbose_name='Carga Horária Semanal'),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='dtfim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='dtinicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='empresa',
            field=models.ForeignKey(db_column='cnpj', on_delete=django.db.models.deletion.PROTECT, to='val_estagio.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='tce',
            field=models.ForeignKey(db_column='apolice_seguro', on_delete=django.db.models.deletion.PROTECT, to='val_estagio.tce', verbose_name='TCE'),
        ),
        migrations.AlterField(
            model_name='relatoriosemestral',
            name='coordenador',
            field=models.ForeignKey(db_column='matricula_coordenador', on_delete=django.db.models.deletion.CASCADE, to='val_estagio.aluno', verbose_name='Coordenador'),
        ),
        migrations.AlterField(
            model_name='relatoriosemestral',
            name='data_envio',
            field=models.DateField(verbose_name='Data de Envio'),
        ),
        migrations.AlterField(
            model_name='relatoriosemestral',
            name='estagio',
            field=models.ForeignKey(db_column='id_estagio', on_delete=django.db.models.deletion.CASCADE, to='val_estagio.estagio', verbose_name='Estágio'),
        ),
        migrations.AlterField(
            model_name='relatoriosemestral',
            name='horas_estagiadas',
            field=models.PositiveIntegerField(verbose_name='Horas Estagiadas'),
        ),
        migrations.AlterField(
            model_name='relatoriosemestral',
            name='semestre',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='O semestre deve estar no formato 26.1 ou 26.2', regex='^\\d{2}\\.[12]$')], verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='relatoriosemestral',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20, verbose_name='Status do Relatório'),
        ),
        migrations.AlterField(
            model_name='tce',
            name='aluno',
            field=models.ForeignKey(db_column='matricula_aluno', on_delete=django.db.models.deletion.CASCADE, to='val_estagio.aluno', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='tce',
            name='apoliceseguro',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Apólice de Seguro'),
        ),
        migrations.AlterField(
            model_name='tce',
            name='bolsa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bolsa'),
        ),
        migrations.AlterField(
            model_name='tce',
            name='secretaria',
            field=models.ForeignKey(db_column='matricula_secretaria', on_delete=django.db.models.deletion.PROTECT, to='val_estagio.secretaria', verbose_name='Secretaria'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='unidade',
            field=models.CharField(choices=[('barra', 'Barra'), ('botafogo', 'Botafogo')], max_length=20, verbose_name='Unidade'),
        ),
    ]
