# Generated by Django 6.0 on 2026-05-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0002_alter_aluno_cpf_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaria',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
