# Generated by Django 6.0 on 2026-05-18 18:44

import django.core.validators
import django.db.models.deletion
import val_estagio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0002_alter_coordenador_options_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('endereco_empresa', models.CharField(max_length=180, verbose_name='Endereço da Empresa')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[val_estagio.validators.validar_cnpj])),
            ],
        ),
        migrations.CreateModel(
            name='Seguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apolice_seguro', models.PositiveIntegerField(unique=True, verbose_name='Apolice de Seguro')),
                ('nome_seguradora', models.CharField(max_length=100, verbose_name='Nome da Seguradora')),
            ],
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[val_estagio.validators.validar_cpf]),
        ),
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de inicio')),
                ('data_fim', models.DateField(verbose_name='Data de fim')),
                ('carga_horaria', models.PositiveIntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='val_estagio.aluno')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='val_estagio.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioSemestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_estagiadas', models.PositiveIntegerField()),
                ('em_aberto', models.BooleanField(default=True)),
                ('semestre', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='O semestre deve estar no formato 26.1 ou 26.2', regex='^\\d{2}\\.[12]$')])),
                ('data_envio', models.DateField(verbose_name='Data de envio')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='val_estagio.aluno')),
                ('estagio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='val_estagio.estagio')),
            ],
        ),
        migrations.CreateModel(
            name='Tce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auxilio_bolsa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='val_estagio.aluno')),
                ('empresa_contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='val_estagio.empresa', verbose_name='Empresa Contratante')),
                ('seguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='val_estagio.seguradora')),
            ],
        ),
        migrations.AddField(
            model_name='estagio',
            name='tce',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='val_estagio.tce'),
        ),
    ]
