# Generated by Django 6.0 on 2026-05-21 10:50

import val_estagio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0003_alter_relatoriosemestral_options_alter_aluno_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, validators=[val_estagio.validators.validar_matricula], verbose_name='Matrícula'),
        ),
    ]
