# Generated by Django 6.0 on 2026-05-31 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0003_secretaria_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretaria',
            name='ativo',
        ),
    ]
