# Generated by Django 6.0 on 2026-05-21 11:10

import val_estagio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0004_alter_usuario_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cep',
            field=models.CharField(max_length=9, validators=[val_estagio.validators.validar_cep], verbose_name='CEP'),
        ),
    ]
