# Generated by Django 6.0 on 2026-06-07 21:54

import encrypted_model_fields.fields
import val_estagio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0004_remove_secretaria_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=encrypted_model_fields.fields.EncryptedCharField(unique=True, validators=[val_estagio.validators.validar_cnpj], verbose_name='CNPJ'),
        ),
    ]
