# Generated by Django 6.0 on 2026-05-21 12:07

import val_estagio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0005_alter_empresa_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='periodo',
            field=models.PositiveIntegerField(validators=[val_estagio.validators.validar_periodo], verbose_name='Período'),
        ),
    ]
