# Generated by Django 6.0 on 2026-06-07 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0005_empresa_id_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='val_estagio.empresa', verbose_name='Empresa'),
        ),
    ]
