# Generated by Django 6.0 on 2026-05-21 12:30

import val_estagio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0006_alter_aluno_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tce',
            name='apoliceseguro',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, validators=[val_estagio.validators.validar_positivo], verbose_name='Apólice de Seguro'),
        ),
        migrations.AlterField(
            model_name='tce',
            name='bolsa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[val_estagio.validators.validar_positivo], verbose_name='Bolsa'),
        ),
    ]
