# Generated by Django 6.0 on 2026-06-10 22:43

import encrypted_model_fields.fields
import val_estagio.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0007_aluno_cpf_hash_empresa_cnpj_hash_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=encrypted_model_fields.fields.EncryptedCharField(unique=True, validators=[val_estagio.validators.validar_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=encrypted_model_fields.fields.EncryptedCharField(unique=True, validators=[val_estagio.validators.validar_cnpj], verbose_name='CNPJ'),
        ),
    ]
