# Generated by Django 6.0 on 2026-05-21 13:16

import django.db.models.deletion
import val_estagio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0007_alter_tce_apoliceseguro_alter_tce_bolsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriosemestral',
            name='coordenador',
            field=models.ForeignKey(db_column='matricula_coordenador', on_delete=django.db.models.deletion.CASCADE, to='val_estagio.coordenador', verbose_name='Coordenador'),
        ),
        migrations.AlterField(
            model_name='relatoriosemestral',
            name='horas_estagiadas',
            field=models.PositiveIntegerField(validators=[val_estagio.validators.validar_positivo], verbose_name='Horas Estagiadas'),
        ),
        migrations.AlterUniqueTogether(
            name='relatoriosemestral',
            unique_together={('estagio', 'semestre')},
        ),
    ]
