# Generated by Django 6.0 on 2026-05-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0008_alter_relatoriosemestral_coordenador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tce',
            name='apoliceseguro',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Apólice de Seguro'),
        ),
    ]
