# Generated by Django 6.0 on 2026-06-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0009_alter_aluno_cpf_hash_alter_empresa_cnpj_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaria',
            name='carteiraDeTrabalho',
            field=models.IntegerField(default=0, verbose_name='carteira de trabalho'),
        ),
    ]
