# Generated by Django 6.0 on 2026-05-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0009_alter_tce_apoliceseguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tce',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20, verbose_name='Status do TCE'),
        ),
    ]
