# Generated by Django 6.0 on 2026-05-25 21:33

import val_estagio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0010_tce_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriosemestral',
            name='semestre',
            field=models.CharField(max_length=4, validators=[val_estagio.validators.validar_semestre], verbose_name='Semestre'),
        ),
    ]
