# Generated by Django 6.0 on 2026-05-28 00:48

import phonenumber_field.modelfields
import val_estagio.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0011_alter_relatoriosemestral_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR', validators=[val_estagio.validators.validar_telefone], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR', validators=[val_estagio.validators.validar_telefone], verbose_name='Telefone'),
        ),
    ]
