@startsalt
{^"Painel Administrativo - Secretaria"
    Busca por Aluno: | "Nome ou Matrícula      " | [ Pesquisar ]
    --
    {#
        <b>Aluno    |<b>Matricula | <b>Data | <b>Status | <b>Ação
        John Textor  |192072683951| 10/04/26 | Pendente | [ Avaliar ]
        John Lock |198204780234| 12/04/26 | Em Análise | [ Avaliar ]
        John F. Kennady |202680278465| 14/04/26 | Pendente | [ Avaliar ]
    }
}
@endsalt