@startsalt
{^"Painel Administrativo - Secretaria"
    Busca por Aluno: | "Nome ou Matrícula      " | [ Pesquisar ]
    --
    {#
        <b>Chamado | <b>Aluno | <b>Data | <b>Status | <b>Ação
        #001 | João Silva | 10/04/26 | Pendente | [ Avaliar ]
        #002 | Maria Souza | 12/04/26 | Em Análise | [ Avaliar ]
        #003 | Pedro Alves | 14/04/26 | Pendente | [ Avaliar ]
    }
}
@endsalt