# Generated by Django 6.0 on 2026-06-10 19:22

import encrypted_model_fields.fields
import val_estagio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0006_alter_empresa_id_alter_estagio_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnpj_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=encrypted_model_fields.fields.EncryptedCharField(validators=[val_estagio.validators.validar_cnpj], verbose_name='CNPJ'),
        ),
    ]
