# Generated by Django 6.0 on 2026-06-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('val_estagio', '0008_alter_aluno_cpf_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
